apiVersion: v1
kind: Service
metadata:
  name: fluentd-aggregator-prometheus-service
  namespace: fluentd
spec:
  ports:
    - name: 24224tcp-fluentd-aggregator-prometheus
      protocol: TCP
      port: 24231
      targetPort: 24231
  selector:
    name: fluentd-aggregator
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
